### ISSUE TITLE
slider rotation showing navigation without images

### ISSUE THREAD

**Issue by stopfstedt** [ucsf-web-services/ucsf_installprofile#1]
on a vanilla install, the second and fourth image on the homepage slider is broken.
![selection_001](https://cloud.githubusercontent.com/assets/1410427/3616145/cf85aeac-0dcf-11e4-89d7-61d76fded597.png)

**Comment by Okami-** [comment]
http://local.installprofile.ucsf.edu/sites/default/files/styles/ucsf_square…umbnail/public/field/image/news/abstract-q-c-1024-768-5.jpeg?itok=Z2P8Qpip 500 (Internal Server Error) 

go to /webroot/sites/default/files/styles the folder is name x-1.x instead of ucsf_square_thumbnail etc etc

**Comment by stopfstedt** [comment]
@Okami- ^^ how is that related?

**Comment by stopfstedt** [comment]
on second look, this does not seem to be an issue with broken images after all, but a mismatch between images in the slider (two), and navigation elements (four). The slider rotates four times, showing navigation without image every other turn.

![selection_002](https://cloud.githubusercontent.com/assets/1410427/3619791/5af6843e-0df8-11e4-865e-873cc459307c.png)

**Comment by stopfstedt** [comment]
its a views configuration issue.
in the "Slider (Content)" view, change the "Formatter" of the "(field_slider_images_collection) Field: Image" field from "flexislider" to "Image", then pick the image style "flexislider_full".

![selection_003](https://cloud.githubusercontent.com/assets/1410427/3620381/a28da71c-0dff-11e4-83ac-5a691a24f4b5.png)

see also: https://www.drupal.org/node/1837996

now re-export the view and plug it into the install profile.
